# Generated by Django 5.2.17 on 2026-10-01 13:34

from django.db import migrations, models


def backfill_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_superuser=True).update(role="superadmin")
    User.objects.filter(is_superuser=False, is_staff=True).update(role="staff")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("staff", "Staff"),
                    ("superadmin", "Super admin"),
                ],
                default="student",
                max_length=12,
            ),
        ),
        migrations.RunPython(backfill_roles, migrations.RunPython.noop),
    ]
