# Generated by Django 5.2.17 on 2026-09-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="gateway_order_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
