# Generated by Django 5.2.17 on 2026-09-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_batches"),
        ("enrollments", "0002_gateway_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="courses.batch",
            ),
        ),
    ]
