# Generated by Django 5.2.17 on 2026-09-30 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_swap_instructor_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("reading", "Reading"),
                            ("live", "Live or in-person class"),
                            ("assignment", "Assignment"),
                        ],
                        default="video",
                        max_length=12,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Position within the course"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Video link, document link or meeting link",
                    ),
                ),
                (
                    "session_at",
                    models.DateTimeField(
                        blank=True, help_text="For live or in-person classes", null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "order", "id"],
            },
        ),
    ]
