# Generated by Django 5.2.17 on 2026-09-30 20:10

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="e.g. Weekday evenings", max_length=100),
                ),
                (
                    "days",
                    models.CharField(
                        help_text="Comma-separated, e.g. Mon,Wed,Fri",
                        max_length=40,
                        validators=[courses.models.validate_days],
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave empty to use the course start date",
                        null=True,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        help_text="e.g. In person. Leave empty to use the course format",
                        max_length=100,
                    ),
                ),
                (
                    "seats",
                    models.PositiveIntegerField(
                        blank=True, help_text="Leave empty for unlimited", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "batches",
                "ordering": ["course", "start_time", "id"],
            },
        ),
    ]
