# Generated by Django 5.2.17 on 2026-10-01 17:27

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, help_text='An uploaded recording. Takes priority over the link above when both are set.', null=True, upload_to='lesson_videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'm4v']), courses.models.validate_video_size]),
        ),
    ]
